<template>
  <div class="loadingio-spinner-bean-eater-0k86eehwy45">
    <div class="ldio-kq1p63ybbhn">
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Loading',
});
</script>

<style type="text/css" scoped>
/* pacman ::: start */
@keyframes ldio-kq1p63ybbhn-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-kq1p63ybbhn-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-kq1p63ybbhn > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-kq1p63ybbhn > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #000115;
  animation: ldio-kq1p63ybbhn-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-kq1p63ybbhn > div:nth-child(2) div:nth-child(2) {
  animation: ldio-kq1p63ybbhn-2 1s linear infinite;
}
.ldio-kq1p63ybbhn > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-kq1p63ybbhn-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-kq1p63ybbhn > div:nth-child(1) {
  display: block;
}
.ldio-kq1p63ybbhn > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #ffffff;
  animation: ldio-kq1p63ybbhn-3 1s linear infinite;
}
.ldio-kq1p63ybbhn > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-kq1p63ybbhn > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-kq1p63ybbhn > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-0k86eehwy45 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
}
.ldio-kq1p63ybbhn {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kq1p63ybbhn div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
/* pacman ::: end */
</style>
